#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("com.xamarin.AndroidIconics.Resource", IsApplication=false)]

namespace com.xamarin.AndroidIconics
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010001
			public static int iiv_color = 2130771969;
			
			// aapt resource value: 0x7f010000
			public static int iiv_icon = 2130771968;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f02000c
			public static int app_name = 2130837516;
			
			// aapt resource value: 0x7f020000
			public static int define_AndroidIconics = 2130837504;
			
			// aapt resource value: 0x7f020001
			public static int library_AndroidIconics_author = 2130837505;
			
			// aapt resource value: 0x7f020002
			public static int library_AndroidIconics_authorWebsite = 2130837506;
			
			// aapt resource value: 0x7f020008
			public static int library_AndroidIconics_isOpenSource = 2130837512;
			
			// aapt resource value: 0x7f020004
			public static int library_AndroidIconics_libraryDescription = 2130837508;
			
			// aapt resource value: 0x7f020003
			public static int library_AndroidIconics_libraryName = 2130837507;
			
			// aapt resource value: 0x7f020005
			public static int library_AndroidIconics_libraryVersion = 2130837509;
			
			// aapt resource value: 0x7f020006
			public static int library_AndroidIconics_libraryWebsite = 2130837510;
			
			// aapt resource value: 0x7f020007
			public static int library_AndroidIconics_licenseId = 2130837511;
			
			// aapt resource value: 0x7f02000a
			public static int library_AndroidIconics_owner = 2130837514;
			
			// aapt resource value: 0x7f020009
			public static int library_AndroidIconics_repositoryLink = 2130837513;
			
			// aapt resource value: 0x7f02000b
			public static int library_AndroidIconics_year = 2130837515;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] IconicsImageView = new int[] {
					2130771968,
					2130771969};
			
			// aapt resource value: 1
			public static int IconicsImageView_iiv_color = 1;
			
			// aapt resource value: 0
			public static int IconicsImageView_iiv_icon = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
